#!/bin/bash

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.bash.d/dircolors && eval "$(dircolors -b ~/bash.d/dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias l='ls -CF'
    alias la='ls -A'
    alias ll='ls -l'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias acs="apt-cache search"
alias addroot="su root -c 'stty -echo; /usr/bin/ssh-add -c -t 12h /root/.ssh/id_rsa; stty echo'"
alias agi="apt-get -s install"
alias astyle="astyle --style=linux --indent-col1-comments --indent=tab --indent-preprocessor --pad-header --align-pointer=type --keep-one-line-blocks --suffix=none"
alias condact="source /site/x86/anaconda-1.8/anaconda/bin/activate"
alias condeact="source /site/x86/anaconda-1.8/anaconda/bin/deactivate"
alias convertbw="convert -density 300 -colorspace gray"
alias e="emacsclient -t"
alias ec="emacsclient -c -a emacs"
alias ed="emacs --daemon"
alias ek="emacsclient -e '(kill-emacs)'"
alias gue="git config user.email 'trevor.keller@gmail.com'"
alias i3lock="/usr/bin/i3lock -c 659ccc"
alias ifstat="sudo iftop -i enp0s31f6"
alias kernperf="perf stat -e cycles,instructions,cache-references,cache-misses,branches,branch-misses,task-clock,faults,minor-faults,context-switches,migrations -r 3"
alias mmspstyle="/usr/bin/astyle --style=linux --indent-col1-comments --indent=tab --indent-preprocessor --indent-preproc-cond --pad-header --align-pointer=type --keep-one-line-blocks --suffix=none"
alias p="python 2>/dev/null"
alias rsync="rsync -Pavz"
alias time="/usr/bin/time -f' Time (%E wall, %U user, %S sys)'"
alias vg="valgrind -v --log-file=val.log --leak-check=full --show-leak-kinds=all --trace-children=yes"
alias wnv="watch -n 1 nvidia-smi"
