#!/bin/bash
me=$(whoami)
# === Manage search paths ===
export PATH=$PATH:/usr/local/bin:$HOME/research/projects/mmsp/utility
export PATH=$PATH:/opt/intel/bin:/opt/pgi/linux86-64/2017/bin
if [[ -d /usr/local/${me} ]]; then
    export PATH=$PATH:/usr/local/${me}/bin
fi
export MMSP_PATH=$HOME/research/projects/mmsp
export PATH=$PATH:$MMSP_PATH/utility
# === AUR ===
export gaur="https://aur.archlinux.org"
# === Emacs ===
export ALTERNATE_EDITOR=""
export EDITOR="/usr/bin/emacsclient -nw"
export VISUAL="/usr/bin/emacsclient -nw"
export TERMINAL=/usr/bin/konsole
export EMACSD=/tmp/emacs-${me}
export EMACSBD=$EMACSD/backups
export EMACSSD=$EMACSD/saves
if [[ ! -d $EMACSD ]]; then
    mkdir -p $EMACSD
    mkdir -p $EMACSBD
    mkdir -p $EMACSSD
fi
# === GO ===
export GOBIN=$GOPATH/bin
export GOROOT=/usr/lib/go
# === KDE ===
export KDE_FULL_SESSION=true
export KDEWM=/usr/bin/i3
# === MPI ===
export MPI_PATH=/usr/local/include
# === NVM ===
if [[ -d ${HOME}/.nvm ]]; then
    export NVM_DIR="/home/thor/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
fi
# === Qt ===
if [[ -d /usr/local/lib/plugins ]]
then
    export QT_QPA_PLATFORM_PLUGIN_PATH=/usr/local/lib/plugins
fi
# === Machine-specific Tasks ===
if [[ $(hostname -s) == "p859561" ]]; then
    unset MAIL
    export CHROME_CONFIG_HOME=/usr/local/${me}
    export CHROME_USER_DATA_HOME=/usr/local/${me}/google-chrome
    export AMGX_DIR=/usr/local/tnk10/opt/AMGX
    export GSL_PATH=$HOME/.conda/envs/mmsp/include
    export MPI_PATH=$HOME/.conda/envs/mmsp/include
    if [[ $(echo $PATH | grep anaconda) == "" ]]; then
        export PATH=$PATH:/site/x86/anaconda-1.8/anaconda/bin
        export LIBGL_ALWAYS_INDIRECT=1
    fi
fi
# === CUDA ===
for n in {9.1,9.0,8.5,8.0,7.5,7.0}; do
    if [[ -d "/usr/local/cuda-${n}" ]]; then
        export PATH=$PATH:/usr/local/cuda-${n}/bin
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-${n}/targets/x86_64-linux/lib/
    fi
done
# === Intel ===
if [[ -d /usr/local/intel ]]; then
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(find /usr/local/intel -type d -name intel64)
elif [[ -d /cluster/intel ]]; then
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(find /cluster/intel -type d -name intel64)
elif [[ $(hostname -s) == "thrudvang" ]]; then
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/intel/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64_lin
    export AMGX_DIR=/Valhalla/arch/AMGX
fi
# === PGI ===
if [[ -f /opt/pgi/license.dat ]]; then
    export PGI_PATH=/opt/pgi
    export LM_LICENSE_FILE=/opt/pgi/license.dat
    export PATH=$PATH:/opt/pgi/linux86-64/2016/bin
elif [[ -f /usr/local/pgi/license.dat ]]; then
    export PGI_PATH=/usr/local/pgi
    export LM_LICENSE_FILE=/usr/local/pgi/license.dat
    export PATH=$PATH:/usr/local/pgi/linux86-64/2016/bin
fi

if [[ -f $HOME/.bash.d/tokens ]]; then
    . ~/.bash.d/tokens
fi
