#!/bin/bash
# === Colorful! ===
BLACK="\[\033[0;30m\]"
BLUE="\[\033[0;34m\]"
GREEN="\[\033[0;32m\]"
CYAN="\[\033[0;36m\]"
RED="\[\033[0;31m\]"
PURPLE="\[\033[0;35m\]"
YELLOW="\[\033[0;33m\]"
GREY="\[\033[0;37m\]"
BLACKB="\[\033[1;30m\]"
BLUEB="\[\033[1;34m\]"
BROWN="\[\033[1;32m\]"
CYANB="\[\033[1;36m\]"
REDB="\[\033[1;31m\]"
PURPLEB="\[\033[1;35m\]"
BROWNB="\[\033[1;33m\]"
GREYB="\[\033[1;37m\]"
NONE="\[\033[0m\]"
# === Non-Interactive! ===
if [[ -z "$Environ_Sourced" && -f /etc/profile ]]
then
    source /etc/profile
fi
# === Prompt! ===
if [ "$PS1" ]
then
	force_color_prompt=yes
    # Turn on automatic directory spelling correction (for 'cd'),
    # checking for removed commands, and saving multi-line commands
    # on one line in the history
    shopt -s cdspell checkhash cmdhist

    # Turn off HUP on exit, mail notification, and using $PATH for
    # the 'source' command
    shopt -u huponexit mailwarn sourcepath

    function prompt_command
    {
        if [ "$?" = 0 ]
        then
            ERRPROMPT=""
        else
            ERRPROMPT="($?)"
        fi
    }
    PROMPT_COMMAND=prompt_command
    # Put current user@machine:/directory on headline of xterms
    case $TERM in
        iris-ansi*|*xterm*|*rxvt*|screen)
        PS="${RED}\${ERRPROMPT}${BLUE}\!"
        if [ $UID = $EUID -a $UID -ne 0 ]
        then
            PS="${PS} ${BROWN}\h${BLUE}% ${NONE}"
        else
            PS="${PS} ${RED}\u@\h${BLUE}# ${NONE}"
        fi
	    PS1="${PURPLE}<${GREEN}\D{%H:%M}${REDB}@${GREEN}\h${RED}:${CYAN}\W${PURPLE}>${RED}\$ ${NONE}"
    ;;
    default)
        if [ $UID = $EUID -a $UID -ne 0 ]
        then
            PS1="\${ERRPROMPT}\! \h$% "
        else
            PS1="\${ERRPROMPT}\! \u@\h$#"
        fi
    esac
fi
# === Resourceful! ===
if [ -f $HOME/.bash.d/aliases ]
then
    source $HOME/.bash.d/aliases
fi
if [ -f $HOME/.bash.d/envs ]
then
    source $HOME/.bash.d/envs
fi
