#!/bin/bash
[ -d "${HOME}/bin"        ] && \
    PATH="${PATH}:${HOME}/bin"
[ -d "${HOME}/.local/bin" ] && \
    PATH="${PATH}:${HOME}/.local/bin"
[ -d "/usr/local/${USER}" ] && \
    PATH="${PATH}:/usr/local/${USER}/bin"
export PATH
