#!/bin/bash
# Built with help from https://github.com/jessfraz/dotfiles

# Unless we're interactive, do nothing
case $- in
	*i*) ;;
	*) return;;
esac

# disable Ctrl-S <https://twitter.com/thingskatedid/status/1348860793618456581>
[[ $- == *i* ]] && \
    stty -ixon

# detect chroot environment
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
	debian_chroot=$(cat /etc/debian_chroot)
fi

# detect color capabilities and set basic prompt
if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	PS1='${debian_chroot:+($debian_chroot)}\[\e[01;32m\]\u@\h\[\e[00m\]:\[\e[01;34m\]\w\[\e[00m\]\$ '
    if [ -x /usr/bin/dircolors ]; then
        if [[ -r ~/.dircolors ]]; then
            eval "$(dircolors -b ~/.dircolors)"
        else
            eval "$(dircolors -b)"
        fi
    fi
else
	PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi

# X11 interface glitter
[[ -f "${HOME}/.dotfiles/x11/xsessionrc" ]] && \
    source "${HOME}/.dotfiles/x11/xsessionrc"

# auxiliary config
for CONF in alias env prompt shopt tools; do
    [[ -f "${HOME}/.dotfiles/bash/${CONF}.sh" ]] && \
        source "${HOME}/.dotfiles/bash/${CONF}.sh"
done
for CONF in "${HOME}"/.dotfiles/bash/opt/*.sh; do
    source "${CONF}"
done

unset CONF
